name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y git openjdk-11-jdk unzip wget \
          build-essential libffi-dev python3-dev python3-pip \
          libssl-dev libsqlite3-dev libjpeg-dev libpng-dev libncurses5-dev \
          libfreetype6-dev gstreamer1.0-plugins-base libgstreamer1.0-dev \
          libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
          libx11-dev libxext-dev libxrender-dev libxrandr-dev \
          libxcursor-dev libxi-dev libxinerama-dev libxss-dev \
          libpulse-dev libudev-dev libusb-dev libinput-dev \
          libegl1-mesa-dev libfontconfig1 libbz2-dev python3-setuptools

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install --user cython buildozer
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

    - name: Install Android SDK and Build-Tools for Buildozer
      run: |
        # مجلد Buildozer الافتراضي للـ SDK
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        cd $HOME/.buildozer/android/platform/android-sdk

        # تحميل أدوات سطر الأوامر
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest

        export PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH

        # قبول جميع تراخيص SDK تلقائيًا
        yes | sdkmanager --licenses

        # تثبيت Build-Tools و Platform-Tools
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        # إضافة المسارات للبيئة
        echo "export PATH=$HOME/.buildozer/android/platform/android-sdk/platform-tools:$HOME/.buildozer/android/platform/android-sdk/build-tools/33.0.2:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tahadi-apk
        path: bin/*.apk
