name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Git
      run: |
        sudo apt update
        sudo apt install -y git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt install -y build-essential libffi-dev python3-dev python3-pip \
          libssl-dev libsqlite3-dev libjpeg-dev libpng-dev libncurses5-dev \
          libfreetype6-dev gstreamer1.0-plugins-base libgstreamer1.0-dev \
          libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev \
          libx11-dev libxext-dev libxrender-dev libxrandr-dev \
          libxcursor-dev libxi-dev libxinerama-dev libxss-dev \
          libpulse-dev libudev-dev libusb-dev libinput-dev \
          libegl1-mesa-dev libfontconfig1 libbz2-dev \
          unzip wget openjdk-11-jdk

        pip install cython
        pip install buildozer

    - name: Install Android SDK and AIDL
      run: |
        ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      env:
        ANDROIDSDK: $HOME/android-sdk
        PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/build-tools/33.0.2:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH:/usr/bin/git:$PATH
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: tahadi-apk
        path: bin/*.apk
